// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: emqx.proto

package emqx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Emqx_Ping_FullMethodName = "/emqx.Emqx/Ping"
)

// EmqxClient is the client API for Emqx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmqxClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type emqxClient struct {
	cc grpc.ClientConnInterface
}

func NewEmqxClient(cc grpc.ClientConnInterface) EmqxClient {
	return &emqxClient{cc}
}

func (c *emqxClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Emqx_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmqxServer is the server API for Emqx service.
// All implementations must embed UnimplementedEmqxServer
// for forward compatibility.
type EmqxServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEmqxServer()
}

// UnimplementedEmqxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmqxServer struct{}

func (UnimplementedEmqxServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEmqxServer) mustEmbedUnimplementedEmqxServer() {}
func (UnimplementedEmqxServer) testEmbeddedByValue()              {}

// UnsafeEmqxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmqxServer will
// result in compilation errors.
type UnsafeEmqxServer interface {
	mustEmbedUnimplementedEmqxServer()
}

func RegisterEmqxServer(s grpc.ServiceRegistrar, srv EmqxServer) {
	// If the following call pancis, it indicates UnimplementedEmqxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Emqx_ServiceDesc, srv)
}

func _Emqx_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmqxServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Emqx_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmqxServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Emqx_ServiceDesc is the grpc.ServiceDesc for Emqx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Emqx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emqx.Emqx",
	HandlerType: (*EmqxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Emqx_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emqx.proto",
}
