// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: emqx.proto

package server

import (
	"context"

	"emqx/emqx"
	"emqx/internal/logic"
	"emqx/internal/svc"
)

type EmqxServer struct {
	svcCtx *svc.ServiceContext
	emqx.UnimplementedEmqxServer
}

func NewEmqxServer(svcCtx *svc.ServiceContext) *EmqxServer {
	return &EmqxServer{
		svcCtx: svcCtx,
	}
}

func (s *EmqxServer) Ping(ctx context.Context, in *emqx.Request) (*emqx.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
