// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: emqx.proto

package emqxclient

import (
	"context"

	"emqx/emqx"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = emqx.Request
	Response = emqx.Response

	Emqx interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultEmqx struct {
		cli zrpc.Client
	}
)

func NewEmqx(cli zrpc.Client) Emqx {
	return &defaultEmqx{
		cli: cli,
	}
}

func (m *defaultEmqx) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := emqx.NewEmqxClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
